name: ML CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
 
      - name: Run Linting
        run: flake8 .
 
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pytest
 
      - name: Run tests
        run: pytest test_model.py
 
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Deploy Model
        run: |
          echo "Deploying model to production (mock)"
          # Here you can add real deployment steps, e.g., Docker, AWS, etc.